In [2]:
import numpy as np
import copy
infinity = 99999
s_min = infinity
big_value = 9999

class TreeNode:
    def __init__(self, size, matrix, parent=None):
        self.s0 = 0
        self.s = 0
        self.parent = parent
        self.n = size
        self.matrix = matrix
        self.f_start_point = np.arange(0, self.n, 1).tolist()
        self.f_end_point = np.arange(0, self.n, 1).tolist()
        self.s_start_point = np.arange(0, self.n, 1).tolist()
        self.s_end_point = np.arange(0, self.n, 1).tolist()
        self.zeros = []
        self.second_row_j = np.array([])
        self.second_clm_i = np.array([])
        global n0
        self.P = [i for i in range(0,n0)]

def normalize(m):
    for i in range(0, m.n):
        corect(m)
        m.s += min(m.matrix[i])
        m.matrix[i] -= min(m.matrix[i])
    for j in range(0, m.n):
        corect(m)
        m.s += min(m.matrix[:,j])
        m.matrix[:,j] -= min(m.matrix[:,j])
    m.s0 = m.s


def corect(m):
    for i in range(0, m.n):
        for j in range(0, m.n):
            if m.matrix[i,j] >= big_value:
                m.matrix[i,j]=infinity
    
def zeros_and_second_el(m):
    for i in range(0, m.n):
        for j in range(0, m.n):
            if m.matrix[i,j] == 0:
                m.zeros.append([i,j,0])
    for number in m.zeros:
        corect(m)
        m_copy = copy.deepcopy(m.matrix)
        m_copy[number[0], number[1]] = infinity
        number[2] += min(m_copy[number[0]])
        number[2] += min(m_copy[:,number[1]])
        pos = np.array(m.zeros)[:,2].tolist().index(max(np.array(m.zeros)[:,2]))
        i = m.zeros[pos][0]
        j = m.zeros[pos][1]
    return max(np.array(m.zeros)[:,2]), i, j

def work_with_lines(m, d, i, j):
    m.f_start_point, m.f_end_point, m.s_start_point, m.s_end_point = copy.deepcopy(m.parent.f_start_point), copy.deepcopy(m.parent.f_end_point), copy.deepcopy(m.parent.s_start_point), copy.deepcopy(m.parent.s_end_point)
    start_of_line = m.f_end_point[i]
    end_of_line = m.s_start_point[j]
    m.P = copy.deepcopy(m.parent.P)
    m.P[start_of_line] = end_of_line
    i_pos_inf = m.f_end_point.index(m.s_end_point[j])
    j_pos_inf = m.s_start_point.index(m.f_start_point[i])
    m.matrix[i_pos_inf, j_pos_inf] = infinity
    m.f_start_point[i_pos_inf] = m.f_start_point[i]
    m.s_end_point[j_pos_inf] = m.s_end_point[j]
    del m.f_start_point[i], m.f_end_point[i], m.s_start_point[j], m.s_end_point[j]
    m.matrix = np.delete(m.matrix, (i), axis=0)
    m.matrix = np.delete(m.matrix, (j), axis=1)
    m.s = m.parent.s
    
def final_proc(m):
    global p_opt
    global s_min
    zero=[]
    if m.matrix[0][0] == 0:
        zero.append([0, 0])
    if m.matrix[0][1] == 0:
        zero.append([0, 1])
    if m.matrix[1][0] == 0:
        zero.append([1, 0])
    if m.matrix[1][1] == 0:
        zero.append([1, 1])
    start_of_first_line = m.f_end_point[zero[0][0]]
    end_of_first_line = m.s_start_point[zero[0][1]]
    start_of_second_line = m.f_end_point[zero[1][0]]
    end_of_second_line = m.s_start_point[zero[1][1]]
    m.P[start_of_first_line] = end_of_first_line
    m.P[start_of_second_line] = end_of_second_line
    p_opt = copy.deepcopy(m.P)
    s_min = m.s
    del lst[0]


matrix =  np.array([[infinity, 68, 73, 24,70,9],[58,infinity,16,44,11,92],[63,9,infinity,86,13,18],[17,34,76,infinity,52,70],[60,18,3,45,infinity,58],[16,82,11,60,48,infinity]])
n0 = len(matrix)
p_opt = np.ones(n0)
root = TreeNode(n0, matrix)
normalize(root)
lst = [root]
print(matrix)
while (len(lst)!=0):
    node = lst[0]
    if node.s < s_min:
        if node.n == 2:
            final_proc(node)
        else:
            d, i, j = zeros_and_second_el(node)
            node.matrix[i,j] = infinity
            child_matrix = copy.deepcopy(node.matrix)
            child = TreeNode(node.n - 1, child_matrix, node)
            work_with_lines(child, d, i, j)
            normalize(node)
            normalize(child)
            lst.insert(0, child)
    else:
        del lst[0]
print ("Длина пути", s_min)#214305
start_city = 0
i = start_city
print("Порядок посещения городов:", i, p_opt[i], end=' ')
i = p_opt[i]
while i > 0:
    i = p_opt[i]
    print(i, end=' ')

[[99999    59    64     0    61     0]
 [   47 99999     5    18     0    81]
 [   54     0 99999    62     4     9]
 [    0    17    59 99999    35    53]
 [   57    15     0    27 99999    55]
 [    5    71     0    34    37 99999]]
Длина пути 102
Порядок посещения городов: 0 5 2 1 4 3 0 